name: build_contents_page
on: [push]
  # schedule:
  # - cron: "* * * * *"
jobs:
  resources:
    name: update resources
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: parser directory structure
        run: python3 content_directory/directory_parser.py
      
      - name: update contents page
        uses: test-room-7/action-update-file@v1
        with:
          file-path: _pages/notes.md
          commit-msg: increment counter
          github-token: ${{ secrets.GITHUB_TOKEN }}
