name: build_contents_page
on:
  schedule:
  - cron: "* * * * *"
jobs:
  update_contents_page:
    name: update contents page from directory structure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: install node
        uses: actions/setup-node@v1

      - name: install HTML beautify
        run: npm i -g js-beautify
      
      - name: parse directory structure
        run: python3 content_directory/directory_parser.py
      
      - name: update contents page
        uses: test-room-7/action-update-file@v1
        with:
          file-path: _pages/notes.md
          commit-msg: increment counter
          github-token: ${{ secrets.GITHUB_TOKEN }}
