name: build_contents_page
on: [push]
  # schedule:
  # - cron: "* * * * *"
jobs:
  ds_change:
    name: check if directory structure changed
    outputs:
      ds_updated: ${{ steps.set_updated.outputs.ds_updated }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: check if directory changed
        id: set_updated
        run: |
          change=`git diff --name-only --diff-filter=RAD HEAD^ HEAD`
          if [ -z $change ]; then
            echo "::set-output name=ds_updated::false"
          else
            echo "::set-output name=ds_updated::true"
          fi

  update_contents_page:
    name: update contents page from directory structure
    needs: ds_change
    if: needs.ds_change.outputs.ds_updated == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: install node
        uses: actions/setup-node@v1

      - name: install HTML beautify
        run: npm i -g js-beautify
      
      - name: parse directory structure
        run: python3 content_directory/directory_parser.py
      
      - name: update contents page
        uses: test-room-7/action-update-file@v1
        with:
          file-path: _pages/notes.md
          commit-msg: increment counter
          github-token: ${{ secrets.GITHUB_TOKEN }}
